name: bloc_presentation
description: Extends blocs with an additional stream which can serve as a way of indicating single-time events (so-called "presentation events").
version: 0.1.1
homepage: https://github.com/leancodepl/bloc_presentation

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_hooks: ^0.18.1
  nested: ^1.0.0
  provider: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  leancode_lint: ^1.0.2
  mocktail: ^0.2.0
