name: bloc_presentation_test
description: A testing library for Blocs/Cubits which mixin BlocPresentationMixin. To be used with bloc_presentation package.
version: 1.0.0-pre.1
homepage: https://github.com/leancodepl/bloc_presentation/tree/master/packages/bloc_presentation_test

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  bloc: ^8.0.0
  bloc_presentation: ^0.4.0
  diff_match_patch: ^0.4.1
  flutter:
    sdk: flutter
  meta: ^1.9.1
  mocktail: ^1.0.0
  test: ^1.24.3

dev_dependencies:
  equatable: ^2.0.5
  leancode_lint: '>=5.0.0'
