name: bloc_presentation_test_example
description: bloc_presentation_test example

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.15.1 <4.0.0'

dependencies:
  bloc: ^8.0.0
  bloc_presentation: ^0.2.1+1
  bloc_presentation_test:
    path: ..
  bloc_test: ^9.1.2
  flutter:
    sdk: flutter
  test: ^1.24.3

dev_dependencies:
  leancode_lint: '>=5.0.0'

dependency_overrides:
  bloc_presentation:
    path: ../../bloc_presentation
