name: bloc_presentation_example
description: A new Flutter project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  bloc_presentation:
    path: ..
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  leancode_lint: ">=5.0.0 <7.0.0"

flutter:
  uses-material-design: true
